### ISSUE TITLE
Script no longer working?

### ISSUE THREAD

**Issue by akiratoriyama** [manojmj92/subtitle-downloader#16]
The command prompt stays open with no response on every video file I tried.

**Comment by core-code** [comment]
i'm also getting this now every time

ama - S01E04.mkv
('Error', (<type 'exceptions.KeyboardInterrupt'>, KeyboardInterrupt(), <traceback object at 0x102626248>))
Error in fetching subtitle for /Volumes/Multimedia/Serien/_____/Futurama/Futurama - S01E05.mkv
('Error', (<class 'urllib2.HTTPError'>, HTTPError(), <traceback object at 0x1026260e0>))
Error in fetching subtitle for /Volumes/Multimedia/Serien/_____/Futurama/Futurama - S01E06.mkv
('Error', (<class 'urllib2.HTTPError'>, HTTPError(), <traceback object at 0x102626320>))
Error in fetching subtitle for /Volumes/Multimedia/Serien/_____/Futurama/Futurama - S01E07.mkv
('Error', (<class 'urllib2.HTTPError'>, HTTPError(), <traceback object at 0x1026264d0>))
Error in fetching subtitle for /Volumes/Multimedia/Serien/_____/Futurama/Futurama - S01E08.mkv
('Error', (<class 'urllib2.HTTPError'>, HTTPError(), <traceback object at 0x102626680>))

**Comment by anselal** [comment]
Error in fetching subtitle for Blackish.S02E06.HDTV.x264-FLEET.mp4
Error (<class 'urllib.error.HTTPError'>, HTTPError(), <traceback object at 0x76668800>)

Both with python2 and python3

**Comment by sjs7007** [comment]
It's probably because the API used for fetching subtitles "http://thesubdb.com/api/" doesn't seem to be properly working anymore.
