### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by kinkate18nic** [manojmj92/subtitle-downloader#27]
Command prompt says:
No Module named 'request'

**Comment by marauderlabs** [comment]
@kinkate18nic  can you please provide whole error? and also your python version?

**Comment by kinkate18nic** [comment]
Here is the screenshot of the error. I have python 3.5.1
![suberror](https://cloud.githubusercontent.com/assets/18030277/14065103/b2f91c18-f439-11e5-9a9c-1b2ffbd51355.png)

**Comment by marauderlabs** [comment]
This is the same [Issue-25](https://github.com/manojmj92/subtitle-downloader/issues/25)

**Comment by kinkate18nic** [comment]
Thanks, I installed requests and its working now. Btw, as mentioned in [Issue 22](https://github.com/manojmj92/subtitle-downloader/issues/22), it worked only after moving subtitle-downloader.py in a location where it doesn't need to have permission and then changed the Subtitle.cmd accordingly.

Great script by the way..:D

**Comment by manojmj92** [comment]
@kinkate18nic Can you give a PR for this?
