### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by sagcan** [manojmj92/subtitle-downloader#31]
So I've followed the instructions of the README.md file and recognized that the script wouldn't work for me (Ubuntu 16.04). There were 2 Issues on my side:   
1) ~/.gnome2/nautilus-scripts is probably deprecated and hence no longer supported (?) -- see https://help.ubuntu.com/community/NautilusScriptsHowto
2) I needed a XML Parser for Python which wasn't written down as a requirement. 

To solve those Issues:
1) place the scripts in here: **~/.local/share/nautilus/scripts/** and don't forget to make it executable
2) type in: **sudo apt install python2.7-lxml** to download the XML-Parser

**Comment by deadcoder0904** [comment]
Close this as README.md is updated and merged at [#1428324](https://github.com/manojmj92/subtitle-downloader/commit/14283243cfbae2e31a203280c9c2790a8a0721a1)
