### ISSUE TITLE
instructions aren't clear 

### ISSUE THREAD

**Issue by harry0099** [manojmj92/subtitle-downloader#64]
If anyone follows the instructions specified in the readme.MD file it won't run because of installation-of-libraries (bs4, requests, click) **didn't specify**.  @manojmj92 did you intentionally not specified it?

**Comment by abspython** [comment]
The installation procedure is documented well in the README file. You should check yourself before posting this kind of question.

P.S : Look again. Every second step is to install the libraries via pip.

**Comment by harry0099** [comment]
@abspython , It was me who added those [instructions] (https://github.com/manojmj92/subtitle-downloader/pull/65). 

P.S : Don't be harsh. This ain't Facebook.

**Comment by abspython** [comment]
I'm really sorry about the rude behavior. I thought the question was dubious.
